version: 2.1
workflows:
    build:
      jobs:
        - build
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t entregasos/frontend:$CIRCLE_BRANCH .
      - run: docker push entregasos/frontend:$CIRCLE_BRANCH