version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t entregasos/frontend:$CIRCLE_BUILD_NUM .
  
  build-and-publish:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t entregasos/frontend:$CIRCLE_BUILD_NUM .
      - run: docker push entregasos/frontend:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - build-and-publish:
          filters:
            branches:
              only:
                - master